import 'package:flutter/material.dart';
import 'package:ibaapp/crud/model.dart';
import 'package:ibaapp/crud/notifier.dart';

class Friends extends StatefulWidget {
  const Friends({super.key});

  @override
  State<Friends> createState() => _FriendsState();
}

class _FriendsState extends State<Friends> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Firebase'),
      ),
      floatingActionButton: FloatingActionButton(
          elevation: 0.0,
          onPressed: () {
            Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => const CourseAddScreen()));
          },
          child: const Icon(Icons.add)),
      body: RefreshIndicator(
        onRefresh: () =>
            FirestoreHelper.getCollectionEntries(FireBaseCollection.coursesRef),
        child: FutureBuilder<List<Course>>(
          future: FirestoreHelper.getCollectionEntries(
              FireBaseCollection.coursesRef),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator());
            } else if (snapshot.hasError) {
              return Text('Error: ${snapshot.error}');
            } else if (!snapshot.hasData || snapshot.data!.isEmpty) {
              return const Center(child: Text('No data available'));
            } else {
              return ListView.builder(
                itemCount: snapshot.data!.length,
                itemBuilder: (context, index) {
                  var item = snapshot.data![index];

                  return Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8.0),
                    child: ListTile(
                      title: Text(item.name ?? ''),
                      subtitle: Text(item.id ?? ''),
                      leading: CircleAvatar(
                        child: ClipRRect(
                          child: Image.network(
                            item.logo ?? '',
                          ),
                        ),
                      ),
                    ),
                  );
                },
              );
            }
          },
        ),
      ),
    );
  }
}

class CourseAddScreen extends StatefulWidget {
  const CourseAddScreen({super.key});

  @override
  _CourseAddScreenState createState() => _CourseAddScreenState();
}

class _CourseAddScreenState extends State<CourseAddScreen> {
  final TextEditingController _codeController1 = TextEditingController();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _logoController = TextEditingController();
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _logoController.text = DummyLogoLinks.logoUrl2;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Text Fields Example'),
      ),
      floatingActionButton: FloatingActionButton(
          elevation: 0.0,
          onPressed: () async {
            await FirestoreHelper.addEntryWithAutogeneratedId(
                FireBaseCollection.coursesRef,
                Course(
                        id: _codeController1.text,
                        name: _nameController.text,
                        logo: _logoController.text)
                    .toJson());
          },
          child: const Icon(Icons.golf_course)),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
            TextField(
              controller: _codeController1,
              decoration: const InputDecoration(labelText: 'Code'),
            ),
            const SizedBox(height: 20),
            TextField(
              controller: _nameController,
              decoration: const InputDecoration(labelText: 'Course Name'),
            ),
            const SizedBox(height: 20),
            TextField(
              controller: _logoController,
              decoration: const InputDecoration(labelText: 'CourseLogo'),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }
}

class DummyLogoLinks {
  static String logoUrl1 =
      'https://images.pexels.com/photos/943096/pexels-photo-943096.jpeg?auto=compress&cs=tinysrgb&w=800';
  static String logoUrl2 =
      'https://images.pexels.com/photos/574070/pexels-photo-574070.jpeg?auto=compress&cs=tinysrgb&w=800';
}
